// Generated by scripts/generate_native_i18n.mjs. Do not edit.
import Foundation

enum NativeI18n {
    static let fallbackLanguageCode = "en"
    static let supportedLanguageCodes: [String] = [
        "en",
        "de",
        "fr",
        "nl",
        "da",
        "fi",
        "sv",
        "el",
        "lv",
        "lt",
        "lb",
        "mt",
        "nb",
        "nn",
        "pl",
        "pt",
        "es",
        "cs",
        "hu",
        "sl",
        "it",
        "rm",
        "tr",
    ]

    static func text(_ key: String, defaultValue: String = "") -> String {
        let value = NSLocalizedString(key, comment: "")
        if value == key {
            return defaultValue.isEmpty ? key : defaultValue
        }
        return value
    }
}
