// Generated by scripts/generate_native_i18n.mjs. Do not edit.
package de.woladen.android.service

internal object GeneratedNativeI18n {
    const val FALLBACK_LANGUAGE_CODE: String = "en"
    val SUPPORTED_LANGUAGE_CODES: Set<String> = setOf(
        "en",
        "de",
        "fr",
        "nl",
        "da",
        "fi",
        "sv",
        "el",
        "lv",
        "lt",
        "lb",
        "mt",
        "nb",
        "nn",
        "pl",
        "pt",
        "es",
        "cs",
        "hu",
        "sl",
        "it",
        "rm",
        "tr",
    )
}
