#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, "..");
const WEB_I18N = path.join(ROOT, "web", "i18n.mjs");
const WEB_I18N_DIR = path.join(ROOT, "web", "i18n");
const ANDROID_RES_DIR = path.join(ROOT, "android", "app", "src", "main", "res");
const ANDROID_NATIVE_I18N_PATH = path.join(
  ROOT,
  "android",
  "app",
  "src",
  "main",
  "java",
  "de",
  "woladen",
  "android",
  "service",
  "GeneratedNativeI18n.kt",
);
const IOS_STRINGS_PATH = path.join(ROOT, "iphone", "Woladen", "Resources", "Localizable.xcstrings");
const IOS_INFO_PLIST_STRINGS_PATH = path.join(ROOT, "iphone", "Woladen", "Resources", "InfoPlist.xcstrings");
const IOS_NATIVE_I18N_PATH = path.join(ROOT, "iphone", "Woladen", "Models", "GeneratedNativeI18n.swift");

function readText(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function parseSupportedLanguages(source) {
  const match = source.match(/export const SUPPORTED_LANGUAGES = \[([\s\S]*?)\];/);
  if (!match) {
    throw new Error("Could not parse SUPPORTED_LANGUAGES from web/i18n.mjs");
  }
  return Array.from(match[1].matchAll(/"([^"]+)"/g), (item) => item[1]);
}

function parseFallbackBundle(source) {
  const match = source.match(/const FALLBACK_BUNDLE = (\{[\s\S]*?\n\});/);
  if (!match) {
    throw new Error("Could not parse FALLBACK_BUNDLE from web/i18n.mjs");
  }
  return vm.runInNewContext(`(${match[1].replace(/;$/, "")})`);
}

function deepMerge(base, patch) {
  const result = { ...base };
  for (const [key, value] of Object.entries(patch || {})) {
    if (
      value &&
      typeof value === "object" &&
      !Array.isArray(value) &&
      base[key] &&
      typeof base[key] === "object" &&
      !Array.isArray(base[key])
    ) {
      result[key] = deepMerge(base[key], value);
    } else {
      result[key] = value;
    }
  }
  return result;
}

function flattenBundle(value, prefix = "") {
  const result = {};
  for (const [key, child] of Object.entries(value || {})) {
    const next = prefix ? `${prefix}.${key}` : key;
    if (child && typeof child === "object" && !Array.isArray(child)) {
      Object.assign(result, flattenBundle(child, next));
    } else if (child !== undefined && child !== null) {
      result[next] = String(child);
    }
  }
  return result;
}

function androidResourceName(key) {
  return `i18n_${key.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")}`;
}

function androidValuesDirectories(language) {
  if (language === "en") {
    return ["values", "values-en"];
  }
  return [`values-${language}`];
}

function escapeAndroidString(value) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "\\'")
    .replace(/%/g, "%%")
    .replace(/\r?\n/g, "\\n");
}

function escapeIOSString(value) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\r?\n/g, "\\n");
}

function readLanguageOverlay(language) {
  const filePath = path.join(WEB_I18N_DIR, `${language}.json`);
  if (!fs.existsSync(filePath)) {
    return {};
  }
  return JSON.parse(readText(filePath));
}

function writeAndroidResources(languages, flattenedBundles, keys) {
  const english = flattenedBundles.en;
  for (const language of languages) {
    for (const directoryName of androidValuesDirectories(language)) {
      const valuesDir = path.join(ANDROID_RES_DIR, directoryName);
      fs.mkdirSync(valuesDir, { recursive: true });
      const stringsPath = path.join(valuesDir, "strings.xml");
      const body = [
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
        "<resources>",
        "    <!-- Generated by scripts/generate_native_i18n.mjs. Do not edit by hand. -->",
        "    <string name=\"app_name\">woladen</string>",
        ...keys.map((key) => {
          const name = androidResourceName(key);
          const value = escapeAndroidString(flattenedBundles[language][key] ?? english[key] ?? key);
          return `    <string name="${name}">${value}</string>`;
        }),
        "</resources>",
        "",
      ].join("\n");
      fs.writeFileSync(stringsPath, body, "utf8");
    }
  }
}

function writeIOSStringCatalog(languages, flattenedBundles, keys) {
  const english = flattenedBundles.en;
  const strings = {
    app_name: {
      extractionState: "manual",
      localizations: Object.fromEntries(
        languages.map((language) => [
          language,
          { stringUnit: { state: "translated", value: "woladen" } },
        ]),
      ),
    },
  };

  for (const key of keys) {
    strings[key] = {
      extractionState: "manual",
      localizations: Object.fromEntries(
        languages.map((language) => [
          language,
          {
            stringUnit: {
              state: "translated",
              value: escapeIOSString(flattenedBundles[language][key] ?? english[key] ?? key),
            },
          },
        ]),
      ),
    };
  }

  const catalog = {
    sourceLanguage: "en",
    strings,
    version: "1.0",
  };

  fs.mkdirSync(path.dirname(IOS_STRINGS_PATH), { recursive: true });
  fs.writeFileSync(IOS_STRINGS_PATH, `${JSON.stringify(catalog, null, 2)}\n`, "utf8");
}

function writeIOSInfoPlistStringCatalog(languages, flattenedBundles) {
  const english = flattenedBundles.en;
  const usageDescriptionKey = "location.usageDescription";
  const strings = {
    NSLocationWhenInUseUsageDescription: {
      extractionState: "manual",
      localizations: Object.fromEntries(
        languages.map((language) => [
          language,
          {
            stringUnit: {
              state: "translated",
              value: escapeIOSString(
                flattenedBundles[language][usageDescriptionKey] ??
                  english[usageDescriptionKey] ??
                  "woladen uses your location to show charging points nearby.",
              ),
            },
          },
        ]),
      ),
    },
  };

  const catalog = {
    sourceLanguage: "en",
    strings,
    version: "1.0",
  };

  fs.mkdirSync(path.dirname(IOS_INFO_PLIST_STRINGS_PATH), { recursive: true });
  fs.writeFileSync(IOS_INFO_PLIST_STRINGS_PATH, `${JSON.stringify(catalog, null, 2)}\n`, "utf8");
}

function writeIOSNativeI18n(languages) {
  const body = [
    "// Generated by scripts/generate_native_i18n.mjs. Do not edit.",
    "import Foundation",
    "",
    "enum NativeI18n {",
    "    static let fallbackLanguageCode = \"en\"",
    "    static let supportedLanguageCodes: [String] = [",
    ...languages.map((language) => `        "${language}",`),
    "    ]",
    "",
    "    static func text(_ key: String, defaultValue: String = \"\") -> String {",
    "        let value = NSLocalizedString(key, comment: \"\")",
    "        if value == key {",
    "            return defaultValue.isEmpty ? key : defaultValue",
    "        }",
    "        return value",
    "    }",
    "}",
    "",
  ].join("\n");
  fs.mkdirSync(path.dirname(IOS_NATIVE_I18N_PATH), { recursive: true });
  fs.writeFileSync(IOS_NATIVE_I18N_PATH, body, "utf8");
}

function writeAndroidNativeI18n(languages) {
  const body = [
    "// Generated by scripts/generate_native_i18n.mjs. Do not edit.",
    "package de.woladen.android.service",
    "",
    "internal object GeneratedNativeI18n {",
    "    const val FALLBACK_LANGUAGE_CODE: String = \"en\"",
    "    val SUPPORTED_LANGUAGE_CODES: Set<String> = setOf(",
    ...languages.map((language) => `        "${language}",`),
    "    )",
    "}",
    "",
  ].join("\n");
  fs.mkdirSync(path.dirname(ANDROID_NATIVE_I18N_PATH), { recursive: true });
  fs.writeFileSync(ANDROID_NATIVE_I18N_PATH, body, "utf8");
}

const source = readText(WEB_I18N);
const languages = parseSupportedLanguages(source);
const fallback = parseFallbackBundle(source);
const flattenedBundles = Object.fromEntries(
  languages.map((language) => {
    const bundle = deepMerge(fallback, readLanguageOverlay(language));
    return [language, flattenBundle(bundle)];
  }),
);
const allKeys = Array.from(
  new Set(Object.values(flattenedBundles).flatMap((bundle) => Object.keys(bundle))),
).sort();

writeAndroidResources(languages, flattenedBundles, allKeys);
writeIOSStringCatalog(languages, flattenedBundles, allKeys);
writeIOSInfoPlistStringCatalog(languages, flattenedBundles);
writeIOSNativeI18n(languages);
writeAndroidNativeI18n(languages);

console.log(`Generated native i18n resources for ${languages.length} languages.`);
