name: Woladen
options:
  bundleIdPrefix: de.woladen
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    INFOPLIST_FILE: Woladen/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: de.woladen.ios
    CODE_SIGN_STYLE: Automatic
targets:
  Woladen:
    type: application
    platform: iOS
    sources:
      - path: Woladen/App
      - path: Woladen/Models
      - path: Woladen/Services
      - path: Woladen/ViewModels
      - path: Woladen/Views
      - path: Woladen/Resources/Assets.xcassets
        buildPhase: resources
      - path: Woladen/Resources/Data
        buildPhase: resources
        type: folder
    settings:
      base:
        ENABLE_DEBUG_DYLIB: NO
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_OUTPUT_FORMAT: xml
        PRODUCT_BUNDLE_IDENTIFIER: de.woladen.ios
        PRODUCT_NAME: Woladen
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Woladen:
    build:
      targets:
        Woladen: all
    run:
      config: Debug
