window.WOLADEN_OPEN_STATIC_API_BASE_URL =
  window.WOLADEN_OPEN_STATIC_API_BASE_URL || "./api/open-static";

window.WOLADEN_OPEN_STATIC_FEATURE_LIMIT =
  window.WOLADEN_OPEN_STATIC_FEATURE_LIMIT || "";

window.WOLADEN_GEOCODER_API_BASE_URL =
  window.WOLADEN_GEOCODER_API_BASE_URL || "";

window.WOLADEN_OPENING_HOURS_MODULE_URL =
  window.WOLADEN_OPENING_HOURS_MODULE_URL || "";

window.WOLADEN_LIVE_API_BASE_URL =
  window.WOLADEN_LIVE_API_BASE_URL || "./api/live";

window.WOLADEN_COMMERCIAL_API_BASE_URL =
  window.WOLADEN_COMMERCIAL_API_BASE_URL || "./api/commercial";

window.WOLADEN_OCCUPANCY_API_BASE_URL =
  window.WOLADEN_OCCUPANCY_API_BASE_URL || "./api/commercial/v1/mobile";
